In [2]:
import pandas as pd
import random
from faker import Faker
import numpy as np

In [3]:
data=pd.read_csv("manip_raw.csv")
data.describe()

,Unnamed: 0,id,Acceleration 0-100 km/h,Top speed,ER,Total Power,Total Torque,BC,Length,Width,...,Top Speed,Vehicle Status,Maintenance Cost,Charge Cost,Max Payload (kgs),Seats_y,Day,Month,Year,Range
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0,10000.000000
mean,4999.50000,3.013500,5.762290,200.377300,457.834500,261.423100,443.25380,81.396400,4604.475500,1830.056500,...,144.048400,0.930200,1151.734400,54.681100,950.790000,5.508800,15.670900,5.526300,24.0,151.772346
std,2886.89568,1.412911,1.747541,40.309615,20.108544,95.297288,126.85689,1.741944,184.044516,24.097223,...,32.204524,0.254822,513.850108,26.181619,316.415326,1.119575,8.759159,2.874184,0.0,59.261884
min,0.00000,1.000000,3.300000,160.000000,425.000000,150.000000,310.00000,78.000000,4261.000000,1800.000000,...,89.000000,0.000000,244.000000,10.000000,400.000000,4.000000,1.000000,1.000000,24.0,18.012000
25%,2499.75000,2.000000,4.400000,160.000000,450.000000,170.000000,330.00000,82.000000,4607.000000,1802.000000,...,116.000000,1.000000,717.750000,32.000000,679.000000,5.000000,8.000000,3.000000,24.0,116.940000
50%,4999.50000,3.000000,5.700000,190.000000,460.000000,250.000000,430.00000,82.000000,4694.000000,1849.000000,...,144.000000,1.000000,1133.000000,54.000000,947.000000,6.000000,16.000000,6.000000,24.0,155.730750
75%,7499.25000,4.000000,7.400000,233.000000,470.000000,366.000000,493.00000,82.000000,4694.000000,1849.000000,...,172.000000,1.000000,1566.000000,77.000000,1222.000000,7.000000,23.000000,8.000000,24.0,194.190000
max,9999.00000,5.000000,7.900000,261.000000,485.000000,377.000000,660.00000,83.000000,4783.000000,1852.000000,...,200.000000,1.000000,2393.000000,100.000000,1500.000000,7.000000,31.000000,10.000000,24.0,257.722500

In [4]:
data.shape

(10000, 42)

In [5]:
data["Make"].unique()

array(['Tesla 1', 'BMW', 'Hyundai', 'Volkswagen', 'Polestar'],
      dtype=object)

In [6]:
data1=data.drop(['Range (km)','Unnamed: 0', 'Latitude (N)', 'Speed (km/h)','Vehicle Status', 'Wheel Base (mm)',
 'Length (mm)','Width (mm)','Height (mm)','Top Speed','Max Payload (kgs)',
 'Longitude (E)','Vehicle Id','Maintenance Cost','Charge Cost','Charge Time','id','Dates','Day','Month','Year','mgr','Seats_y','Seats_x','Driver'],axis=1)

In [7]:
data1.shape

(10000, 17)

In [8]:
list(data1)

['Make',
 'Acceleration 0-100 km/h',
 'Top speed',
 'ER',
 'Total Power',
 'Total Torque',
 'Drive',
 'BC',
 'Length',
 'Width',
 'Height',
 'Wheelbase',
 'Gross Vehicle Weight (GVWR)',
 'Max. Payload',
 'Cargo Volume',
 'Battery Level (%)',
 'Range']

In [9]:
data1.head(10)

,Make,Acceleration 0-100 km/h,Top speed,ER,Total Power,Total Torque,Drive,BC,Length,Width,Height,Wheelbase,Gross Vehicle Weight (GVWR),Max. Payload,Cargo Volume,Battery Level (%),Range
0,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,89,222.3900
1,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,45,163.6800
2,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,22,54.4920
3,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,15,28.3680
4,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,20,49.5480
5,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,27,78.4680
6,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,42,142.8600
7,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,81,204.2475
8,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,58,138.5025
9,Tesla 1,4.4,233,485,366,493,AWD,82,4694,1849,1443,2875,2232,388,561,22,61.3200

In [10]:
data2=pd.get_dummies(data1,dtype=int)

In [11]:
data2.shape

(10000, 23)

In [12]:
data2.head(5)

,Acceleration 0-100 km/h,Top speed,ER,Total Power,Total Torque,BC,Length,Width,Height,Wheelbase,...,Battery Level (%),Range,Make_BMW,Make_Hyundai,Make_Polestar,Make_Tesla 1,Make_Volkswagen,Drive_AWD,Drive_Front,Drive_Rear
0,4.4,233,485,366,493,82,4694,1849,1443,2875,...,89,222.390,0,0,0,1,0,1,0,0
1,4.4,233,485,366,493,82,4694,1849,1443,2875,...,45,163.680,0,0,0,1,0,1,0,0
2,4.4,233,485,366,493,82,4694,1849,1443,2875,...,22,54.492,0,0,0,1,0,1,0,0
3,4.4,233,485,366,493,82,4694,1849,1443,2875,...,15,28.368,0,0,0,1,0,1,0,0
4,4.4,233,485,366,493,82,4694,1849,1443,2875,...,20,49.548,0,0,0,1,0,1,0,0

In [13]:
y=data2['Range']
X=data2.drop('Range',axis=1)

In [14]:
y

0       222.3900
1       163.6800
2        54.4920
3        28.3680
4        49.5480
          ...
9995    132.0750
9996    168.7350
9997     42.3120
9998    174.3900
9999    232.9275
Name: Range, Length: 10000, dtype: float64

In [15]:
X

,Acceleration 0-100 km/h,Top speed,ER,Total Power,Total Torque,BC,Length,Width,Height,Wheelbase,...,Cargo Volume,Battery Level (%),Make_BMW,Make_Hyundai,Make_Polestar,Make_Tesla 1,Make_Volkswagen,Drive_AWD,Drive_Front,Drive_Rear
0,4.4,233,485,366,493,82,4694,1849,1443,2875,...,561,89,0,0,0,1,0,1,0,0
1,4.4,233,485,366,493,82,4694,1849,1443,2875,...,561,45,0,0,0,1,0,1,0,0
2,4.4,233,485,366,493,82,4694,1849,1443,2875,...,561,22,0,0,0,1,0,1,0,0
3,4.4,233,485,366,493,82,4694,1849,1443,2875,...,561,15,0,0,0,1,0,1,0,0
4,4.4,233,485,366,493,82,4694,1849,1443,2875,...,561,20,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,7.4,160,425,170,330,78,4607,1800,1479,2735,...,405,56,0,0,1,0,0,0,1,0
9996,7.4,160,425,170,330,78,4607,1800,1479,2735,...,405,69,0,0,1,0,0,0,1,0
9997,7.4,160,425,170,330,78,4607,1800,1479,2735,...,405,19,0,0,1,0,0,0,1,0
9998,7.4,160,425,170,330,78,4607,1800,1479,2735,...,405,73,0,0,1,0,0,0,1,0
9999,7.4,160,425,170,330,78,4607,1800,1479,2735,...,405,92,0,0,1,0,0,0,1,0

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [17]:
X_train.head(5)

,Acceleration 0-100 km/h,Top speed,ER,Total Power,Total Torque,BC,Length,Width,Height,Wheelbase,...,Cargo Volume,Battery Level (%),Make_BMW,Make_Hyundai,Make_Polestar,Make_Tesla 1,Make_Volkswagen,Drive_AWD,Drive_Front,Drive_Rear
9069,7.4,160,425,170,330,78,4607,1800,1479,2735,...,405,53,0,0,1,0,0,0,1,0
2603,3.3,261,460,377,660,82,4694,1849,1443,2875,...,561,46,1,0,0,0,0,1,0,0
7738,7.9,160,450,150,310,82,4261,1802,1568,2771,...,385,86,0,0,0,0,1,0,0,1
1579,4.4,233,485,366,493,82,4694,1849,1443,2875,...,561,38,0,0,0,1,0,1,0,0
5058,5.7,190,470,250,430,83,4783,1852,1448,2856,...,470,52,0,1,0,0,0,0,0,1

In [18]:
import pandas as pd

# Display all columns
pd.set_option('display.max_columns', None)

# Now you can view the DataFrame with all columns
X_train.head(5)

,Acceleration 0-100 km/h,Top speed,ER,Total Power,Total Torque,BC,Length,Width,Height,Wheelbase,Gross Vehicle Weight (GVWR),Max. Payload,Cargo Volume,Battery Level (%),Make_BMW,Make_Hyundai,Make_Polestar,Make_Tesla 1,Make_Volkswagen,Drive_AWD,Drive_Front,Drive_Rear
9069,7.4,160,425,170,330,78,4607,1800,1479,2735,2490,496,405,53,0,0,1,0,0,0,1,0
2603,3.3,261,460,377,660,82,4694,1849,1443,2875,2232,388,561,46,1,0,0,0,0,1,0,0
7738,7.9,160,450,150,310,82,4261,1802,1568,2771,2300,447,385,86,0,0,0,0,1,0,0,1
1579,4.4,233,485,366,493,82,4694,1849,1443,2875,2232,388,561,38,0,0,0,1,0,1,0,0
5058,5.7,190,470,250,430,83,4783,1852,1448,2856,2605,555,470,52,0,1,0,0,0,0,0,1

In [19]:
X_test.head(5)

,Acceleration 0-100 km/h,Top speed,ER,Total Power,Total Torque,BC,Length,Width,Height,Wheelbase,Gross Vehicle Weight (GVWR),Max. Payload,Cargo Volume,Battery Level (%),Make_BMW,Make_Hyundai,Make_Polestar,Make_Tesla 1,Make_Volkswagen,Drive_AWD,Drive_Front,Drive_Rear
6252,7.9,160,450,150,310,82,4261,1802,1568,2771,2300,447,385,37,0,0,0,0,1,0,0,1
4684,5.7,190,470,250,430,83,4783,1852,1448,2856,2605,555,470,59,0,1,0,0,0,0,0,1
1731,4.4,233,485,366,493,82,4694,1849,1443,2875,2232,388,561,24,0,0,0,1,0,1,0,0
4742,5.7,190,470,250,430,83,4783,1852,1448,2856,2605,555,470,19,0,1,0,0,0,0,0,1
4521,5.7,190,470,250,430,83,4783,1852,1448,2856,2605,555,470,98,0,1,0,0,0,0,0,1

In [20]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [21]:
ypred =reg.predict(X_test)

In [22]:
ypred

array([106.125  , 156.5    ,  76.15625, ..., 145.96875, 173.9375 ,
       217.5    ])

In [23]:
from sklearn.metrics import r2_score
r2_score(y_test,ypred)

0.8950804974253742

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# Evaluate the model
mse = mean_squared_error(y_test, ypred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, ypred)
r2 = r2_score(y_test, ypred)

# Print the evaluation metrics
print(f"Mean Squared Error : {mse}")
print(f"Root Mean Squared Error : {rmse}")
print(f"Mean Absolute Error : {mae}")
print(f"RÂ² Score : {r2}")

Mean Squared Error : 373.8215396920416
Root Mean Squared Error : 19.334465073853004
Mean Absolute Error : 14.873188833333334
RÂ² Score : 0.8950804974253742

In [25]:
print(reg)
print("Expected input shape:", reg.n_features_in_)  # For scikit-learn models

LinearRegression()
Expected input shape: 22

In [26]:
import pickle

# Save the trained model
with open("sam.pkl", "wb") as file:
    pickle.dump(reg, file)
####in project used this as model.pkl